services:
  polymusic:
    build: .
    container_name: polymusic_app
    restart: always
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
